---
title: "Assignment 1: Introduction"
author: "Aurora McCollum"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on 1/17/22.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took a statistics course in undergrad that was solely focused on R, and have used it in multiples classes before and after that, like calculus and a lot of bio courses where we had to analyze data. Each time I have to relearn a lot because I never use it constantly or consistently enough.

2. Are there any components of the course about which you feel confident?

> Answer: I'm pretty confident that I will remember a lot of the easier coding things (or be able to figure them out)

3. Are there any components of the course about which you feel apprehensive?

> Answer: I have never used a lot of the things we had to download at the beginning so I'm a little worried about what those might entail. I just find R  annoying because of how specific and finicky coding is and this course just sounds like it might be  intense. Plus github is already giving me a lot of trouble, but thanks to John progress is happening! 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/arm132/Environmental_Data_Analytics_2022


